import { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import Dialog from '@mui/material/Dialog';
import DialogContent from '@mui/material/DialogContent';
import { QRCodeSVG } from 'qrcode.react';
import { Bell, Car, CheckCheck, Heart, MessageCircle, Plus, Search, Share2, UserRound } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import StatusBadge from '../components/StatusBadge';
import useApiData from '../hooks/useApiData';
import api from '../services/api';
import { demoForum, demoNotifications, demoVehicles } from '../data/demo';
import { showToast } from '../store/uiSlice';

export function VehiclesPage(){
  const role=useSelector(s=>s.auth.user?.role);const endpoint=role==='Resident'?'/vehicles/my':'/vehicles';const {data,setData}=useApiData(endpoint,demoVehicles);const list=Array.isArray(data)?data:data.items||demoVehicles;const [open,setOpen]=useState(false);const [form,setForm]=useState({vehicleNumber:'',type:'car',make:'',model:'',color:'',parkingSlot:''});const dispatch=useDispatch();
  const add=async(e)=>{e.preventDefault();let v;try{const {data:r}=await api.post('/vehicles',form);v=r.data;}catch{v={...form,_id:`v-${Date.now()}`,isActive:true};}setData([v,...list]);setOpen(false);dispatch(showToast({message:'Vehicle registered'}));};
  return <><PageHeader eyebrow="Parking & access" title={role==='Resident'?'My vehicles':'Vehicle lookup'} description="Keep resident vehicles, parking assignments and gate identification organized." action={role==='Resident'?<button onClick={()=>setOpen(true)} className="btn-primary"><Plus size={18}/> Add vehicle</button>:null}/><div className="grid gap-5 md:grid-cols-2">{list.map(v=><article key={v._id} className="card p-6"><div className="flex items-start justify-between"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-brand-600"><Car/></div><StatusBadge value={v.isActive?'active':'inactive'}/></div><div className="mt-5 font-display text-2xl font-extrabold tracking-wide">{v.vehicleNumber}</div><div className="mt-2 text-sm text-slate-500">{[v.color,v.make,v.model].filter(Boolean).join(' · ')}</div><div className="mt-5 flex items-end justify-between border-t border-slate-100 pt-4 dark:border-slate-800"><div><div className="text-xs uppercase tracking-wider text-slate-400">Parking slot</div><div className="font-bold">{v.parkingSlot||'Not assigned'}</div></div><div className="rounded-xl bg-white p-2 shadow-card"><QRCodeSVG value={v.vehicleNumber} size={52}/></div></div></article>)}</div>
    <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogContent className="!p-7"><h2 className="font-display text-2xl font-extrabold">Register a vehicle</h2><form onSubmit={add} className="mt-6 grid gap-4 sm:grid-cols-2">{[['Vehicle number','vehicleNumber'],['Make','make'],['Model','model'],['Color','color'],['Parking slot','parkingSlot']].map(([l,k])=><label key={k}><span className="mb-2 block text-sm font-bold">{l}</span><input required={k==='vehicleNumber'} className="field" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label><span className="mb-2 block text-sm font-bold">Type</span><select className="field" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{['car','motorcycle','bicycle','scooter','other'].map(x=><option key={x}>{x}</option>)}</select></label><button className="btn-primary sm:col-span-2">Save vehicle</button></form></DialogContent></Dialog></>;
}

export function ForumPage(){
  const {data,setData}=useApiData('/forum/posts',demoForum);const posts=Array.isArray(data)?data:data.items||demoForum;const [category,setCategory]=useState('all');const [open,setOpen]=useState(false);const [form,setForm]=useState({title:'',body:'',category:'general'});const dispatch=useDispatch();
  const create=async(e)=>{e.preventDefault();let p;try{const {data:r}=await api.post('/forum/posts',form);p=r.data;}catch{p={...form,_id:`p-${Date.now()}`,author:{name:'Abhiram Rao'},likes:[],createdAt:new Date().toISOString()};}setData([p,...posts]);setOpen(false);};
  const like=async(p)=>{try{await api.post(`/forum/posts/${p._id}/like`);}catch{}setData(posts.map(x=>x._id===p._id?{...x,likes:[...(x.likes||[]),'me']}:x));};
  const visible=category==='all'?posts:posts.filter(p=>p.category===category);
  return <><PageHeader eyebrow="Neighbourhood conversations" title="Community forum" description="Ask, share, trade and connect with the people around you." action={<button onClick={()=>setOpen(true)} className="btn-primary"><Plus size={18}/> Create post</button>}/><div className="mb-6 flex gap-2 overflow-x-auto pb-2">{['all','general','events','buy-sell','help','feedback'].map(x=><button key={x} onClick={()=>setCategory(x)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold capitalize ${category===x?'bg-brand-600 text-white':'bg-white text-slate-500 dark:bg-slate-900'}`}>{x.replace('-',' / ')}</button>)}</div><div className="mx-auto max-w-3xl space-y-5">{visible.map(p=><article key={p._id} className="card p-6"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-full bg-gradient-to-br from-brand-500 to-violet-500 font-bold text-white">{p.author?.name?.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><div className="font-bold">{p.author?.name}</div><div className="text-xs text-slate-400">{new Date(p.createdAt).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})} · {p.category}</div></div></div><h2 className="mt-5 font-display text-xl font-bold">{p.title}</h2><p className="mt-2 leading-7 text-slate-600 dark:text-slate-300">{p.body}</p><div className="mt-5 flex gap-5 border-t border-slate-100 pt-4 text-sm font-bold text-slate-500 dark:border-slate-800"><button onClick={()=>like(p)} className="flex items-center gap-2 hover:text-red-500"><Heart size={18}/> {p.likes?.length||0}</button><button className="flex items-center gap-2 hover:text-brand-600"><MessageCircle size={18}/> Comment</button><button className="flex items-center gap-2 hover:text-brand-600"><Share2 size={18}/> Share</button></div></article>)}</div>
    <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogContent className="!p-7"><h2 className="font-display text-2xl font-extrabold">Start a discussion</h2><form onSubmit={create} className="mt-6 space-y-4"><input required className="field" placeholder="Post title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea required className="field" rows="6" placeholder="What would you like to share?" value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/><select className="field" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['general','events','buy-sell','help','feedback','other'].map(x=><option key={x}>{x}</option>)}</select><button className="btn-primary w-full">Publish post</button></form></DialogContent></Dialog></>;
}

export function NotificationsPage(){
  const {data,setData}=useApiData('/notifications',demoNotifications);const list=Array.isArray(data)?data:data.items||demoNotifications;const [filter,setFilter]=useState('all');
  const markAll=async()=>{try{await api.patch('/notifications/read-all');}catch{}setData(list.map(n=>({...n,isRead:true})));};
  const visible=filter==='all'?list:list.filter(n=>n.type.includes(filter));
  return <><PageHeader eyebrow="Your updates" title="Notification center" description="Arrivals, approvals, service updates and payment reminders—all in one calm feed." action={<button onClick={markAll} className="btn-secondary"><CheckCheck size={18}/> Mark all read</button>}/><div className="mb-6 flex gap-2 overflow-x-auto">{['all','visitor','complaint','booking','invoice'].map(x=><button key={x} onClick={()=>setFilter(x)} className={`rounded-full px-4 py-2 text-sm font-bold capitalize ${filter===x?'bg-brand-600 text-white':'bg-white text-slate-500 dark:bg-slate-900'}`}>{x}</button>)}</div><section className="card overflow-hidden">{visible.map(n=><button key={n._id} className={`flex w-full gap-4 border-b border-slate-100 p-5 text-left last:border-0 dark:border-slate-800 ${!n.isRead?'bg-blue-50/50 dark:bg-blue-950/20':''}`}><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl ${!n.isRead?'bg-brand-600 text-white':'bg-slate-100 text-slate-500 dark:bg-slate-800'}`}><Bell size={19}/></div><div className="flex-1"><div className="flex justify-between gap-3"><div className="font-bold">{n.title}</div><div className="text-xs text-slate-400">{new Date(n.createdAt).toLocaleDateString('en-IN')}</div></div><div className="mt-1 text-sm text-slate-500">{n.message}</div></div>{!n.isRead&&<span className="mt-2 h-2 w-2 rounded-full bg-brand-600"/>}</button>)}</section></>;
}
