import { Link } from 'react-router-dom';
import { useSelector } from 'react-redux';
import { Bar, Doughnut, Line } from 'react-chartjs-2';
import { Chart as ChartJS, CategoryScale, LinearScale, BarElement, PointElement, LineElement, ArcElement, Tooltip, Legend, Filler } from 'chart.js';
import { BadgeCheck, Bell, CalendarCheck, CircleDollarSign, ClipboardCheck, IndianRupee, Megaphone, Plus, ShieldCheck, Siren, TrendingUp, UserCheck, UsersRound, Wrench } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import StatCard from '../components/StatCard';
import StatusBadge from '../components/StatusBadge';
import { demoComplaints, demoNotices, demoVisitors } from '../data/demo';
import useApiData from '../hooks/useApiData';

ChartJS.register(CategoryScale, LinearScale, BarElement, PointElement, LineElement, ArcElement, Tooltip, Legend, Filler);
const chartOptions = { responsive: true, maintainAspectRatio: false, plugins: { legend: { position: 'bottom', labels: { usePointStyle: true, boxWidth: 8 } } }, scales: { x: { grid: { display: false } }, y: { grid: { color: '#e2e8f055' }, border: { display: false } } } };

export default function DashboardPage() {
  const role = useSelector(s=>s.auth.user?.role);
  if (role === 'Admin' || role === 'SuperAdmin') return <AdminDashboard />;
  if (role === 'Guard') return <SecurityDashboard />;
  if (role === 'Staff') return <StaffDashboard />;
  return <ResidentDashboard />;
}

function ResidentDashboard() {
  const user=useSelector(s=>s.auth.user);
  const {data:notices}=useApiData('/announcements?limit=3',demoNotices);
  const quick=[['Pre-approve visitor',UsersRound,'/app/visitors','blue'],['Raise complaint',Wrench,'/app/complaints','orange'],['Book a facility',CalendarCheck,'/app/bookings','green'],['Pay maintenance',CircleDollarSign,'/app/payments','violet']];
  return <><PageHeader eyebrow="Resident home" title={`Welcome back, ${user?.name?.split(' ')[0]} 👋`} description="A quick look at what needs your attention today." />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="Outstanding due" value="₹2,500" icon={IndianRupee} color="blue" hint="Due tomorrow"/><StatCard title="Visitors today" value="02" icon={UserCheck} color="green" hint="1 currently at gate"/><StatCard title="Open complaints" value="01" icon={Wrench} color="orange" hint="Plumbing · in progress"/><StatCard title="Upcoming bookings" value="03" icon={CalendarCheck} color="violet" hint="Next: Badminton tomorrow"/></div>
    <div className="mt-7 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><section className="card p-6"><div className="flex items-center justify-between"><h2 className="section-title">Quick actions</h2><span className="text-xs text-slate-400">Things you do most</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{quick.map(([label,Icon,to,color])=><Link key={label} to={to} className="flex items-center gap-4 rounded-2xl border border-slate-100 p-4 transition hover:-translate-y-0.5 hover:border-brand-200 hover:shadow-md dark:border-slate-800"><div className={`grid h-11 w-11 place-items-center rounded-2xl ${color==='blue'?'bg-blue-50 text-blue-600':color==='green'?'bg-emerald-50 text-emerald-600':color==='orange'?'bg-orange-50 text-orange-600':'bg-violet-50 text-violet-600'}`}><Icon size={20}/></div><span className="font-bold">{label}</span></Link>)}</div></section>
      <section className="overflow-hidden rounded-3xl bg-gradient-to-br from-red-600 to-rose-700 p-6 text-white shadow-xl shadow-red-600/15"><div className="flex items-start justify-between"><div><div className="text-xs font-bold uppercase tracking-[.16em] text-red-100">Emergency assist</div><h2 className="mt-2 font-display text-2xl font-extrabold">Help is one tap away.</h2></div><Siren size={32}/></div><p className="mt-3 text-sm leading-6 text-red-100">Alert the security desk and community response team with your apartment details.</p><button className="mt-6 rounded-2xl bg-white px-5 py-3 font-bold text-red-600">Activate SOS</button></section>
    </div>
    <div className="mt-7 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><section className="card p-6"><div className="flex justify-between"><h2 className="section-title">Recent notices</h2><Link to="/app/notices" className="text-sm font-bold text-brand-600">View all</Link></div><div className="mt-4 divide-y divide-slate-100 dark:divide-slate-800">{notices.map(n=><div key={n._id} className="flex gap-4 py-4"><div className={`mt-1 h-10 w-1 rounded-full ${n.type==='emergency'?'bg-red-500':n.type==='event'?'bg-emerald-500':'bg-brand-500'}`}/><div><div className="font-bold">{n.title}</div><div className="mt-1 line-clamp-2 text-sm text-slate-500">{n.body}</div></div></div>)}</div></section>
      <section className="card p-6"><h2 className="section-title">This week</h2><div className="mt-5 space-y-4">{[['Tomorrow · 6 PM','Community town hall','Clubhouse'],['Saturday · 8 AM','Yoga on the lawn','Central park'],['Sunday · 10 AM','Safety drill','All blocks']].map(([time,title,place])=><div key={title} className="flex gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-blue-50 text-brand-600"><CalendarCheck size={20}/></div><div><div className="text-xs font-bold text-brand-600">{time}</div><div className="font-bold">{title}</div><div className="text-xs text-slate-400">{place}</div></div></div>)}</div></section></div></>;
}

function AdminDashboard() {
  useApiData('/dashboard/overview',{});
  const labels=['Jan','Feb','Mar','Apr','May','Jun'];
  return <><PageHeader eyebrow="Management overview" title="Good morning, Priya" description="Your community is healthy. Collections are up and resolution time is improving." action={<button className="btn-primary"><Plus size={18}/> Quick create</button>}/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="Total residents" value="1,250" icon={UsersRound} color="blue" trend="4.8%"/><StatCard title="Visitors today" value="87" icon={ShieldCheck} color="green" trend="12%"/><StatCard title="Open complaints" value="15" icon={Wrench} color="orange" hint="3 high priority"/><StatCard title="Revenue this month" value="₹8.25L" icon={TrendingUp} color="violet" trend="8.2%"/></div>
    <div className="mt-7 grid gap-6 xl:grid-cols-[1.4fr_.6fr]"><section className="card p-6"><div className="flex justify-between"><div><h2 className="section-title">Maintenance collection</h2><p className="text-sm text-slate-400">Monthly billed vs collected</p></div><select className="rounded-xl border border-slate-200 px-3 text-sm dark:bg-slate-800"><option>2026</option></select></div><div className="mt-5 h-72"><Bar options={chartOptions} data={{labels,datasets:[{label:'Collected',data:[6.8,7.1,7.4,7.8,8.0,8.25],backgroundColor:'#2563EB',borderRadius:8},{label:'Billed',data:[7.4,7.5,7.8,8.1,8.3,8.6],backgroundColor:'#DBEAFE',borderRadius:8}]}}/></div></section>
      <section className="card p-6"><h2 className="section-title">Complaint health</h2><p className="text-sm text-slate-400">Current distribution</p><div className="mx-auto mt-4 h-60 max-w-xs"><Doughnut options={{...chartOptions,scales:undefined,cutout:'70%'}} data={{labels:['Open','In progress','Resolved'],datasets:[{data:[15,23,84],backgroundColor:['#F97316','#2563EB','#10B981'],borderWidth:0}]}}/></div></section></div>
    <div className="mt-7 grid gap-6 xl:grid-cols-2"><section className="card p-6"><h2 className="section-title">Daily visitor flow</h2><div className="mt-4 h-64"><Line options={chartOptions} data={{labels:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],datasets:[{label:'Visitors',data:[54,68,61,79,87,112,95],borderColor:'#10B981',backgroundColor:'#10B98118',fill:true,tension:.4}]}}/></div></section><section className="card p-6"><div className="flex justify-between"><h2 className="section-title">Needs attention</h2><span className="rounded-full bg-red-50 px-3 py-1 text-xs font-bold text-red-600">5 items</span></div><div className="mt-4 space-y-3">{[['3 resident approvals','New registrations awaiting review','Review'],['2 overdue high-priority issues','Electrical and elevator','Assign'],['₹42,500 overdue','Across 11 units','Remind'],['4 booking requests','Clubhouse and courts','Review']].map(([a,b,c])=><div key={a} className="flex items-center justify-between rounded-2xl border border-slate-100 p-4 dark:border-slate-800"><div><div className="font-bold">{a}</div><div className="text-xs text-slate-400">{b}</div></div><button className="text-sm font-bold text-brand-600">{c}</button></div>)}</div></section></div></>;
}

function SecurityDashboard() {
  const {data}=useApiData('/security/dashboard',{activeVisitors:demoVisitors.filter(v=>v.status==='checked-in'),todayStats:{checkIns:87,checkOuts:65},pendingApprovals:demoVisitors.filter(v=>v.status==='approved')});
  return <><PageHeader eyebrow="Gate operations" title="Security command center" description="Verify, check in and monitor everyone currently inside the community."/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="Currently inside" value={data.activeVisitors?.length || 22} icon={UsersRound} color="blue"/><StatCard title="Check-ins today" value={data.todayStats?.checkIns || 87} icon={UserCheck} color="green"/><StatCard title="Checked out" value={data.todayStats?.checkOuts || 65} icon={ClipboardCheck} color="violet"/><StatCard title="Awaiting approval" value={data.pendingApprovals?.length || 4} icon={Bell} color="orange"/></div>
    <div className="mt-7 grid gap-6 xl:grid-cols-[.75fr_1.25fr]"><section className="rounded-3xl bg-slate-950 p-6 text-white"><ShieldCheck className="text-emerald-400" size={32}/><h2 className="mt-5 font-display text-2xl font-extrabold">Fast gate verification</h2><p className="mt-2 text-sm text-slate-400">Scan a visitor QR or enter the six-digit OTP.</p><Link to="/app/visitors" className="mt-7 inline-flex rounded-2xl bg-brand-600 px-5 py-3 font-bold">Open scanner</Link><div className="mt-8 border-t border-white/10 pt-5"><div className="text-xs uppercase tracking-wider text-slate-500">Emergency desk</div><div className="mt-2 font-bold">Security: +91 90000 10001</div><div className="text-sm text-slate-400">Ambulance: 108 · Fire: 101</div></div></section>
      <section className="card p-6"><div className="flex justify-between"><h2 className="section-title">Live visitors</h2><Link className="text-sm font-bold text-brand-600" to="/app/visitors">View gate log</Link></div><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase text-slate-400"><tr><th className="pb-3">Visitor</th><th>Resident</th><th>Unit</th><th>Status</th></tr></thead><tbody>{[...demoVisitors,{...demoVisitors[1],_id:'v4',name:'Amit Desai'}].map(v=><tr key={v._id} className="border-t border-slate-100 dark:border-slate-800"><td className="py-4 font-bold">{v.name}<div className="text-xs font-normal text-slate-400">{v.purpose}</div></td><td>{v.host?.name}</td><td>{v.unit?.blockName}-{v.unit?.unitNumber}</td><td><StatusBadge value={v.status}/></td></tr>)}</tbody></table></div></section></div></>;
}

function StaffDashboard() {
  const {data}=useApiData('/complaints/assigned/me',demoComplaints);
  const tasks=Array.isArray(data)?data:data.items||demoComplaints;
  return <><PageHeader eyebrow="Maintenance workspace" title="Your assigned work" description="Three tasks are active today. One is marked high priority."/>
    <div className="grid gap-4 sm:grid-cols-3"><StatCard title="Assigned today" value="08" icon={ClipboardCheck} color="blue"/><StatCard title="In progress" value="03" icon={Wrench} color="orange"/><StatCard title="Completed this week" value="26" icon={BadgeCheck} color="green"/></div>
    <section className="card mt-7 p-6"><h2 className="section-title">Priority queue</h2><div className="mt-5 grid gap-4 lg:grid-cols-2">{tasks.map(t=><div key={t._id} className="rounded-2xl border border-slate-100 p-5 dark:border-slate-800"><div className="flex justify-between"><StatusBadge value={t.priority}/><StatusBadge value={t.status}/></div><h3 className="mt-4 font-display text-lg font-bold capitalize">{t.category} request</h3><p className="mt-1 text-sm text-slate-500">{t.description}</p><div className="mt-4 text-xs text-slate-400">{t.raisedBy?.name} · {t.unit?.blockName}-{t.unit?.unitNumber}</div><Link to="/app/complaints" className="mt-5 inline-flex text-sm font-bold text-brand-600">Update progress →</Link></div>)}</div></section></>;
}
