import { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { Camera, KeyRound, Mail, MapPin, Phone, Save, ShieldCheck, UserRound, UsersRound } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import api from '../services/api';
import { showToast } from '../store/uiSlice';

export default function ProfilePage(){
  const user=useSelector(s=>s.auth.user);const dispatch=useDispatch();
  const [form,setForm]=useState({name:user?.name||'',email:user?.email||'',phone:'+91 98765 43210',apartment:'A-1204',emergencyName:'Ananya Rao',emergencyPhone:'+91 99887 76655'});
  const save=async(e)=>{e.preventDefault();try{await api.patch('/residents/profile',{name:form.name,phone:form.phone,emergencyContact:{name:form.emergencyName,phone:form.emergencyPhone,relation:'Family'}});}catch{}dispatch(showToast({message:'Profile updated successfully'}));};
  return <><PageHeader eyebrow="Your account" title="Profile & household" description="Keep your personal, family and emergency information current."/>
    <div className="grid gap-6 xl:grid-cols-[.65fr_1.35fr]"><aside className="card p-6 text-center"><div className="relative mx-auto h-28 w-28"><div className="grid h-full w-full place-items-center rounded-full bg-gradient-to-br from-brand-500 to-violet-600 font-display text-3xl font-extrabold text-white">{user?.name?.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><button className="absolute bottom-0 right-0 grid h-9 w-9 place-items-center rounded-full bg-white text-brand-600 shadow-card"><Camera size={17}/></button></div><h2 className="mt-5 font-display text-xl font-bold">{form.name}</h2><div className="text-sm text-slate-400">{user?.role}</div><div className="mt-6 space-y-3 border-t border-slate-100 pt-5 text-left text-sm dark:border-slate-800"><div className="flex items-center gap-3"><MapPin size={17} className="text-brand-600"/> Skyline Enclave · {form.apartment}</div><div className="flex items-center gap-3"><Mail size={17} className="text-brand-600"/> {form.email}</div><div className="flex items-center gap-3"><Phone size={17} className="text-brand-600"/> {form.phone}</div></div><button className="btn-secondary mt-6 w-full"><KeyRound size={17}/> Change password</button></aside>
      <form onSubmit={save} className="space-y-6"><section className="card p-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-brand-600"><UserRound size={19}/></div><h2 className="section-title">Personal information</h2></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{[['Full name','name','text'],['Email','email','email'],['Phone','phone','tel'],['Apartment','apartment','text']].map(([l,k,t])=><label key={k}><span className="mb-2 block text-sm font-bold">{l}</span><input type={t} className="field" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div></section>
      <section className="card p-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><UsersRound size={19}/></div><h2 className="section-title">Family members</h2></div><div className="mt-5 space-y-3">{[['Ananya Rao','Spouse'],['Aarav Rao','Son']].map(([n,r])=><div key={n} className="flex items-center justify-between rounded-2xl border border-slate-100 p-4 dark:border-slate-800"><div><div className="font-bold">{n}</div><div className="text-xs text-slate-400">{r}</div></div><button type="button" className="text-sm font-bold text-brand-600">Edit</button></div>)}<button type="button" className="text-sm font-bold text-brand-600">+ Add family member</button></div></section>
      <section className="card p-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-red-50 text-red-600"><ShieldCheck size={19}/></div><h2 className="section-title">Emergency contact</h2></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-bold">Contact name</span><input className="field" value={form.emergencyName} onChange={e=>setForm({...form,emergencyName:e.target.value})}/></label><label><span className="mb-2 block text-sm font-bold">Contact phone</span><input className="field" value={form.emergencyPhone} onChange={e=>setForm({...form,emergencyPhone:e.target.value})}/></label></div></section><button className="btn-primary"><Save size={18}/> Save profile changes</button></form></div></>;
}
